### ISSUE TITLE
App crashes on clicking the send button in FilledFormsFragment

### ISSUE THREAD

**Issue by DreamyPhobic** [opendatakit/skunkworks-crow#111]
#### Problem Description:
App crashes when we click on the send button after selecting some forms. 

#### Steps to reproduce:
1. Get a blank form(like All widgets) in collect.
2. Fill it and save it.
3. Now launch Share, and try to send the filled form.
4.  You will notice the crash there.

> java.lang.RuntimeException: Unable to destroy activity {org.odk.share/org.odk.share.activities.SendFormsActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4746)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4764)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by DreamyPhobic** [comment]
I would like to work on it. Thank you.

**Comment by lakshyagupta21** [comment]
I'm not able to reproduce the issue. Can you elaborate on the steps to reproduce the issue? Or Share some screenshot or video to reproduce it.

**Comment by DreamyPhobic** [comment]
![ezgif-1-62852d920df0](https://user-images.githubusercontent.com/33078171/53162067-430fa500-35f1-11e9-9cc0-432fcea9f70f.gif)

Its crashing when we try to send filled form but it doesn't happen with blank forms.. as shown in video.

**Comment by lakshyagupta21** [comment]
I'm still not able to reproduce the issue on my device, can you mention the specification of your test device.
And if possible also attach the crash logs.

**Comment by DreamyPhobic** [comment]
My device - Realme U1, Android 8.1

Yeah, I think its happening with my device only, no issue found on Android 8.0, Moto e5 plus.

**Comment by lakshyagupta21** [comment]
Can you raise a PR for the fix of this crash?

**Comment by DreamyPhobic** [comment]
yeah sure, I will do it.
