### ISSUE TITLE
app crashes on clicking send if location is disabled

### ISSUE THREAD

**Issue by udhay24** [opendatakit/skunkworks-crow#219]
#### Software and hardware versions 
Reproduced the bug in android-8.1  (Samsung j7 2016)
#### Problem description
 trying to send the form when the location is disabled crashes the app.
#### Steps to reproduce the problem
disable the location 
try to send any form
#### Expected behaviour
should ask the user to enable location

#### Error Log when the app crashes:
```2019-03-20 18:58:11.524 16900-16900/org.odk.share E/WifiHotspotHelper: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.odk.share.controller.WifiHotspotHelper.setWifiConfig(WifiHotspotHelper.java:110)
        at org.odk.share.controller.WifiHotspotHelper.disableHotspot(WifiHotspotHelper.java:133)
        at org.odk.share.activities.SendActivity.onCreate(SendActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.SecurityException: App not allowed to read or update stored WiFi AP config (uid = 10357)
        at android.os.Parcel.readException(Parcel.java:2029)
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.net.wifi.IWifiManager$Stub$Proxy.setWifiApConfiguration(IWifiManager.java:2288)
        at android.net.wifi.WifiManager.setWifiApConfiguration(WifiManager.java:2910)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.odk.share.controller.WifiHotspotHelper.setWifiConfig(WifiHotspotHelper.java:110) 
        at org.odk.share.controller.WifiHotspotHelper.disableHotspot(WifiHotspotHelper.java:133) 
        at org.odk.share.activities.SendActivity.onCreate(SendActivity.java:119) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
2019-03-20 18:58:11.524 16900-16900/org.odk.share W/WifiManager: org.odk.share attempted call to setWifiApEnabled: enabled = false
2019-03-20 18:58:11.537 16900-16900/org.odk.share I/WifiManager: startLocalOnlyHotspot() setwifiap packageName : org.odk.share
2019-03-20 18:58:11.542 16900-16900/org.odk.share D/AndroidRuntime: Shutting down VM
2019-03-20 18:58:11.547 16900-16900/org.odk.share E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.share, PID: 16900
    java.lang.RuntimeException: Unable to resume activity {org.odk.share/org.odk.share.activities.SendActivity}: java.lang.SecurityException: Location mode is not enabled.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3805)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3845)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3065)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.SecurityException: Location mode is not enabled.
        at android.os.Parcel.readException(Parcel.java:2029)
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.net.wifi.IWifiManager$Stub$Proxy.startLocalOnlyHotspot(IWifiManager.java:2176)
        at android.net.wifi.WifiManager.startLocalOnlyHotspot(WifiManager.java:2602)
        at org.odk.share.activities.SendActivity.turnOnHotspot(SendActivity.java:352)
        at org.odk.share.activities.SendActivity.initiateHotspot(SendActivity.java:161)
        at org.odk.share.activities.SendActivity.startHotspot(SendActivity.java:153)
        at org.odk.share.activities.SendActivity.onResume(SendActivity.java:257)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1363)
        at android.app.Activity.performResume(Activity.java:7440)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3780)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3845) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3065) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
```

![videotogif_2019 03 20_19 41 13](https://user-images.githubusercontent.com/29946262/54691162-c963cc00-4b48-11e9-8926-d6f735c4ac55.gif)

**Comment by udhay24** [comment]
@shobhitagarwal1612 @lakshyagupta21  can I work on this issue

**Comment by udhay24** [comment]
@Chromicle do you have any guess why this happens?

**Comment by lakshyagupta21** [comment]
Sure @udhay24 go ahead.

**Comment by udhay24** [comment]
@lakshyagupta21 can you assign this to me since i already 3 PR waiting for review

**Comment by udhay24** [comment]
> Settings.Secure.putInt(getContentResolver(), Settings.Secure.LOCATION_MODE, 3)

but this flag will throw security exception above kitkat right?

**Comment by Chromicle** [comment]
Yeah as secure_connections is depend upon root things it will throw exceptions I tried to minimised it that but it is not done

**Comment by shobhitagarwal1612** [comment]
@udhay24 Thank you for reporting the issue and suggesting a solution for the same. You are already working on a number of issues. Please let someone else take this one on.

**Comment by nishontan** [comment]
@opendatakit-bot  claim

**Comment by udhay24** [comment]
@nishontan are you similar problem? if yes can you share me your phone specifications.
