### ISSUE TITLE
IllegalStateException: Caller already has an active LocalOnlyHotspot request

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#255]
#### Software and hardware versions 
Android 8.0 Nexus 6P

#### Problem description
App crashes with log:
```java
     Caused by: java.lang.IllegalStateException: Caller already has an active LocalOnlyHotspot request
        at android.os.Parcel.readException(Parcel.java:2012)
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.net.wifi.IWifiManager$Stub$Proxy.startLocalOnlyHotspot(IWifiManager.java:1661)
        at android.net.wifi.WifiManager.startLocalOnlyHotspot(WifiManager.java:2002)
        at org.odk.share.views.ui.send.SendActivity.turnOnHotspot(SendActivity.java:386)
        at org.odk.share.views.ui.send.SendActivity.initiateHotspot(SendActivity.java:189)
        at org.odk.share.views.ui.send.SendActivity.startHotspot(SendActivity.java:166)
        at org.odk.share.views.ui.send.SendActivity.toggleHotspot(SendActivity.java:494)
        at org.odk.share.views.ui.send.SendActivity.checkLocationPermission(SendActivity.java:467)
        at org.odk.share.views.ui.send.SendActivity.onResume(SendActivity.java:306)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7107)

```

#### Steps to reproduce the problem

1. click the `send` button in main page.
2. select a blank form to sent, hotspot will be enabled automatically.
3. press back button and repeat send operation again with hotspot enabled.
4. click `send` again.
5. app crash.

#### Expected behavior
App not crash, with back button pressed, the hotspot session should be closed.

**Comment by Chromicle** [comment]
Yeah, I observed this behaviour if #227 this will be solved when I checked with that PR

**Comment by huangyz0918** [comment]
@Chromicle Cool, then we can closed this after that.
