### ISSUE TITLE
Java.io.IOException: Socket Closed

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#267]
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
When I'm trying to sending multiple form instances, I have an issue `java.io.IOException: socket closed`, I guess that when I finished the first form transmission, the `UploadJob.java` will close the bluetooth socket so the next form transfer task will have the `socket closed` issue. I don't know whether this issue are the same using WiFi hotspot, the hotspot method didn't work in my device so it's hard for me to test.

#### Steps to reproduce the problem
Send multiple form instances and see the log from the sender device.
```
1970-01-07 13:44:28.451 11862-11953/org.odk.share E/UploadJob: java.io.IOException: socket closed
        at android.net.LocalSocketImpl$SocketOutputStream.flush(LocalSocketImpl.java:167)
        at android.bluetooth.BluetoothSocket.flush(BluetoothSocket.java:491)
        at android.bluetooth.BluetoothOutputStream.flush(BluetoothOutputStream.java:96)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at org.odk.share.tasks.UploadJob.closeConnections(UploadJob.java:147)
        at org.odk.share.tasks.UploadJob.uploadInstances(UploadJob.java:177)
        at org.odk.share.tasks.UploadJob.setupDataStreamsAndRun(UploadJob.java:139)
        at org.odk.share.tasks.UploadJob.initJob(UploadJob.java:112)
        at org.odk.share.tasks.UploadJob.onRunJob(UploadJob.java:98)
        at com.evernote.android.job.Job.runJob(Job.java:132)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:191)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:176)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:159)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

#### Expected behavior
We can transfer multiple forms without any issue.

#### Other information 
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
Fixed in #260
