### ISSUE TITLE
java.net.SocketException: Socket closed using Hotspot

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#292]
#### Software and hardware versions 
This is a common  issue in all kinds of APIs.

#### Problem description
When we are trying to close the hotspot sender, we will get an exception, although this issue has no effects on our feature, we can still  send/receive files.

#### Steps to reproduce the problem
- Start sending forms using hotspot.
- And press back button to cancel the sender job
- See the logs in Android Studio console

```
08-06 17:19:46.134 3517-4457/org.odk.share E/UploadJob: java.net.SocketException: Socket closed
        at libcore.io.Posix.accept(Native Method)
        at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
        at java.net.ServerSocket.implAccept(ServerSocket.java:216)
        at java.net.ServerSocket.accept(ServerSocket.java:140)
        at org.odk.share.tasks.UploadJob.setupDataStreamsAndRun(UploadJob.java:133)
        at org.odk.share.tasks.UploadJob.initJob(UploadJob.java:112)
        at org.odk.share.tasks.UploadJob.onRunJob(UploadJob.java:98)
        at com.evernote.android.job.Job.runJob(Job.java:132)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:191)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:176)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:159)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

#### Expected behavior
No exceptions. 

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment]
@opendatakit-bot label "bug"
