### ISSUE TITLE
App crashes when pressing send button

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/skunkworks-crow#294]
#### Software and hardware versions 
Android v9.0 device used...

#### Problem description
App crashes when user presses send button and there are two entries of same form visible on main screen.(could be a collect issue)
#### Steps to reproduce the problem
Use the directory attached below for both collect and skunkworks-crow app and then open the app and press send button
[odk.zip](https://github.com/opendatakit/skunkworks-crow/files/3475128/odk.zip)
[share.zip](https://github.com/opendatakit/skunkworks-crow/files/3475129/share.zip)

#### Expected behavior
App should not crash

#### Other information 
```
2019-08-07 08:50:25.662 27680-27680/org.odk.share E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.share, PID: 27680
    java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:465)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at android.database.CursorWrapper.getString(CursorWrapper.java:137)
        at org.odk.share.views.ui.instance.adapter.InstanceAdapter.onBindViewHolder(InstanceAdapter.java:57)
        at org.odk.share.views.ui.instance.adapter.InstanceAdapter.onBindViewHolder(InstanceAdapter.java:25)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6890)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6932)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5852)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6119)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3990)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3707)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1631)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:898)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
2019-08-07 08:50:25.662 27680-27680/org.odk.share E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:754)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
        at android.view.Choreographer.doCallbacks(Choreographer.java:984)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-07 08:50:25.663 27680-27703/org.odk.share E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-08-07 08:50:25.663 27680-27680/org.odk.share E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.share, PID: 27680
    java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:465)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at android.database.CursorWrapper.getString(CursorWrapper.java:137)
        at org.odk.share.views.ui.instance.adapter.InstanceAdapter.onBindViewHolder(InstanceAdapter.java:57)
        at org.odk.share.views.ui.instance.adapter.InstanceAdapter.onBindViewHolder(InstanceAdapter.java:25)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6890)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6932)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5852)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6119)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3990)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3707)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1631)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:898)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
2019-08-07 08:50:25.663 27680-27680/org.odk.share E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:754)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
        at android.view.Choreographer.doCallbacks(Choreographer.java:984)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

![screenshot](https://user-images.githubusercontent.com/18495162/62592833-41614180-b8f2-11e9-9348-37dbe09f6827.jpg)

**Comment by Chromicle** [comment]
@lakshyagupta21 yeah it might be collect issue when I am clicking send button with some existing old forms I can't reproduce this issue 
When installed in android 6 I am experiencing this issue with new forms this what I informed in PR #286

**Comment by lakshyagupta21** [comment]
@Chromicle This is not the bug in Collect, in some of the recent commits in skunkworks-crow the default path of odk directory got changed to `sdcard/odk` which I think is not same as the one used by collect.
And in Collect before downloading any form it checks if it has any form at the same path then it doesn't download, otherwise, it goes and downloads the form even if the identical form entry present in db.
So we need to change the default path of `odk` directory in skunkworks-crow, this should resolve the issue.

**Comment by Chromicle** [comment]
Yeah @lakshyagupta21 the default path of odk is changed, 
I have one doubt, there is a edit text(Not Implemented working feature) in which we can change the path of odk  directory what If user changes to new path so did we have to change the path of downloading forms in collect also or else conflict may occur
And we have to move all forms into new path

**Comment by huangyz0918** [comment]
I saw this issue as well, but I cannot reproduce this in my Android 5 device, this appears in my Android 9 device. Is this issue only related to android device?

**Comment by huangyz0918** [comment]
Attached please find the empty (bad) forms
[Biggest N of Set.xml.zip](https://github.com/opendatakit/skunkworks-crow/files/3489457/Biggest.N.of.Set.xml.zip)
[Birds.xml.zip](https://github.com/opendatakit/skunkworks-crow/files/3489458/Birds.xml.zip)

**Comment by lakshyagupta21** [comment]
> I saw this issue as well, but I couldn't reproduce this in my Android 5 device, this appears in my Android 9 device. Is this issue only related to android 9 device?

Not sure. Are you able to reproduce on any of your devices correctly?



> Attached please find the empty (bad) forms
> [Biggest N of Set.xml.zip](https://github.com/opendatakit/skunkworks-crow/files/3489457/Biggest.N.of.Set.xml.zip)
> [Birds.xml.zip](https://github.com/opendatakit/skunkworks-crow/files/3489458/Birds.xml.zip)

How are you saying that these forms are bad forms. I mean is it corrupted, half received or entry in db but not physically present in storage?

**Comment by huangyz0918** [comment]
The examples I sent are blank forms, without root elements.

**Comment by huangyz0918** [comment]
Can you reproduce this issue in your android 7 machine? @lakshyagupta21

**Comment by huangyz0918** [comment]
This is weird, when I deleted the `/storage/odk` in my phone and reinstall both Collect and Skunkworks-crow, this issue didn't appear after that.

**Comment by lakshyagupta21** [comment]
> This is weird, when I deleted the `/storage/odk` in my phone and reinstall both Collect and Skunkworks-crow, this issue didn't appear after that.

I'm not sure about the crash, but reproducing the scenarios where duplication of forms is present can be achieved by following the above steps. And I tried this only in Android 9.

**Comment by lakshyagupta21** [comment]
@huangyz0918 Can you fix this issue, as I'm not able to fill or open any of the forms in collect, it could be due to multiple forms with same formId and formVersion.

**Comment by huangyz0918** [comment]
> Can you fix this issue, as I'm not able to fill or open any of the forms in collect 

Of course, I'll try my best to address, but I may need more time to do some tests since sometimes I cannot reproduce it, now all we know is it can be reproduced in android 9. Let's complete the exist PRs recently, so I can work on this after that.
