### ISSUE TITLE
crash: Crashing on sending Forms through hotspot 

### ISSUE THREAD

**Issue by Chromicle** [opendatakit/skunkworks-crow#323]
#### Software and hardware versions 
Android Samsung J8

#### Problem description
Currently, App is crashing we are trying to send forms for the second time due to we are making a request once again for hotspot 

#### Steps to reproduce the problem
Make the default method as a hotspot 
Select forms and click send button 
Come back again to MainActivty
Select forms once again and click send button
observe the crash 

#### Expected behavior
The App should not have to crash

#### Other information 
Here I am giving log
```
java.lang.RuntimeException: Unable to resume activity {org.odk.share/org.odk.share.views.ui.hotspot.HpSenderActivity}: java.lang.IllegalStateException: Caller already has an active LocalOnlyHotspot request
   at android.os.Parcel.createException(Parcel.java:1974)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.net.wifi.IWifiManager$Stub$Proxy.startLocalOnlyHotspot(IWifiManager.java:2178)
        at android.net.wifi.WifiManager.startLocalOnlyHotspot(WifiManager.java:2551)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.turnOnHotspot(HpSenderActivity.java:377)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.initiateHotspot(HpSenderActivity.java:212)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.startHotspot(HpSenderActivity.java:199)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.toggleHotspot(HpSenderActivity.java:494)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.checkLocationPermission(HpSenderActivity.java:453)
        at org.odk.share.views.ui.hotspot.HpSenderActivity.onResume(HpSenderActivity.java:297)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
```

@opendatakit-bot --claim

**Comment by Chromicle** [comment]
@opendatakit-bot claim

**Comment by shubhamkumar1739** [comment]
@opendatakit-bot claim

**Comment by shubhamkumar1739** [comment]
@opendatakit-bot claim --force

**Comment by shubhamkumar1739** [comment]
@opendatakit-bot claim --force

**Comment by shubhamkumar1739** [comment]
@opendatakit-bot claim --force

**Comment by shubhamkumar1739** [comment]
@opendatakit-bot claim
